# theme.toml template for a Hugo theme
name = "Roxo Hugo"
license = "MIT"
licenselink = "https://github.com/StaticMania/roxo-hugo/blob/master/LICENSE"
description = "Roxo Hugo is a digital agency Hugo theme for creative agencies, freelancers, graphic designers, photographers. Can be used for any kind of corporate websites who provide digital services with many purpose such as Design, Digital Products, Development, Campaign & Content, Employer Branding, Animation & Motion Graphics, Packaging & Product Design, Retail & Spatial, Print & Editorial Design, Concept/Text, Information Design etc."
homepage = "https://roxo-hugo.staticmania.com/"
tags = ["entrepreneurship", "startup cruise", "startup sailing"]
features = ["yachts"]
min_version = "0.58.0"

[author]
  name = "Turquoise Summit"
  homepage = ""
